version = 0.1
[default.deploy.parameters]
stack_name = "AWSMAP"
resolve_s3 = true
s3_prefix = "AWSMAP"
region = "ap-southeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "MapName=\"Cathaymap\" PlaceIndexName=\"CathayPlaceIndex\" RouteCalculatorName=\"RouteCalculatorName\" lambdaFunctionName=\"CognitoAuthCathay\" CognitoAuthName=\"Cathaycognitoauth\""
image_repositories = []
